# -*- coding: utf-8 -*-
"""k-means.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ouCzbKUIWQv637NdE4qwvH6UAYGqQvYb

اول کتابخانه نصب می‌شه.

بعد ازت می‌خواد فایل API رو آپلود کنی.

اگه فایل درست آپلود شد، اون رو می‌بره تو مسیر مناسب و دسترسی‌هاش رو درست می‌کنه
"""

!pip install -q kaggle

from google.colab import files
import os

uploaded = files.upload()

if 'kaggle.json' in uploaded:
    if not os.path.exists('/root/.kaggle'):
        os.makedirs('/root/.kaggle')
    !mv kaggle.json /root/.kaggle/
    !chmod 600 /root/.kaggle/kaggle.json

!kaggle datasets download -d uciml/pima-indians-diabetes-database
!unzip -o pima-indians-diabetes-database.zip

import pandas as pd
import numpy as np

df = pd.read_csv('diabetes.csv')
display(df.head())
display(df.describe())

from sklearn.preprocessing import StandardScaler

cols_with_zeros = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']
df[cols_with_zeros] = df[cols_with_zeros].replace(0, np.nan)
df.fillna(df.mean(), inplace=True)
X = df.drop('Outcome', axis=1)
y = df['Outcome']
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

wcss = []
for i in range(1, 11):
    kmeans = KMeans(n_clusters=i, init='k-means++', n_init=10, random_state=42)
    kmeans.fit(X_scaled)
    wcss.append(kmeans.inertia_)

plt.figure(figsize=(10, 6))
plt.plot(range(1, 11), wcss, marker='o')
plt.title('The Elbow Method')
plt.xlabel('Number of Clusters (k)')
plt.ylabel('WCSS')
plt.grid(True)
plt.show()

from sklearn.decomposition import PCA

kmeans = KMeans(n_clusters=2, init='k-means++', n_init=10, random_state=42)
cluster_labels = kmeans.fit_predict(X_scaled)

pca = PCA(n_components=2)
principalComponents = pca.fit_transform(X_scaled)

pca_df = pd.DataFrame(data=principalComponents, columns=['PC 1', 'PC 2'])
pca_df['Cluster'] = cluster_labels

centroids_pca = pca.transform(kmeans.cluster_centers_)

plt.figure(figsize=(12, 8))
plt.scatter(pca_df['PC 1'], pca_df['PC 2'], c=pca_df['Cluster'], cmap='viridis', alpha=0.6)
plt.scatter(centroids_pca[:, 0], centroids_pca[:, 1], s=300, c='red', marker='X', label='Centroids')
plt.title('K-Means Clusters (Plotted with PCA)')
plt.xlabel('Principal Component 1')
plt.ylabel('Principal Component 2')
plt.legend()
plt.grid(True)
plt.show()

import seaborn as sns
from sklearn.metrics import confusion_matrix, adjusted_rand_score

cm = confusion_matrix(y, cluster_labels)

plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Cluster 0', 'Cluster 1'],
            yticklabels=['Real: No Diabetes', 'Real: Diabetes'])
plt.title('Confusion Matrix')
plt.xlabel('Predicted Cluster from K-Means')
plt.ylabel('Real Health Outcome')
plt.show()

ari_score = adjusted_rand_score(y, cluster_labels)

score_df = pd.DataFrame({'Adjusted Rand Score': [ari_score]})
display(score_df)