# -*- coding: utf-8 -*-
"""mnist-MaxPooling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YYipY_XG0yo2TOjo3KxzsrsylgmqjMsr
"""

import tensorflow as tf
from tensorflow.keras import layers, models
from tensorflow.keras.datasets import fashion_mnist
import matplotlib.pyplot as plt
import numpy as np

(x_train, y_train), (x_test, y_test) = fashion_mnist.load_data()

x_train = x_train / 255.0
x_test = x_test / 255.0

x_train = x_train[..., np.newaxis]
x_test = x_test[..., np.newaxis]

def build_model(pooling_type="max", dropout_rate=0.5,
                kernel_size=3, stride=1, depth=[32, 64, 128]):

    model = models.Sequential()

    model.add(layers.Conv2D(
        depth[0], kernel_size,
        strides=stride,
        padding="same",
        activation='relu',
        input_shape=(28,28,1)
    ))

    if pooling_type == "max":
        model.add(layers.MaxPooling2D(pool_size=(2,2)))
    else:
        model.add(layers.AveragePooling2D(pool_size=(2,2)))

    model.add(layers.Conv2D(
        depth[1], kernel_size,
        strides=stride,
        padding="same",
        activation='relu'
    ))

    if pooling_type == "max":
        model.add(layers.MaxPooling2D(pool_size=(2,2)))
    else:
        model.add(layers.AveragePooling2D(pool_size=(2,2)))

    model.add(layers.Conv2D(
        depth[2], kernel_size,
        strides=stride,
        padding="same",
        activation='relu'
    ))

    model.add(layers.Flatten())

    model.add(layers.Dense(256, activation='relu'))
    model.add(layers.Dropout(dropout_rate))
    model.add(layers.Dense(128, activation='relu'))
    model.add(layers.Dense(64, activation='relu'))
    model.add(layers.Dense(10, activation='softmax'))

    model.compile(
        optimizer='adam',
        loss='sparse_categorical_crossentropy',
        metrics=['accuracy']
    )

    return model

def plot_history(history, title):
    plt.figure(figsize=(12,5))

    plt.subplot(1,2,1)
    plt.plot(history.history['accuracy'], label='Train')
    plt.plot(history.history['val_accuracy'], label='Validation')
    plt.title(f"Accuracy - {title}")
    plt.legend()

    plt.subplot(1,2,2)
    plt.plot(history.history['loss'], label='Train')
    plt.plot(history.history['val_loss'], label='Validation')
    plt.title(f"Loss - {title}")
    plt.legend()

    plt.show()

model_max = build_model(pooling_type="max")

history_max = model_max.fit(
    x_train, y_train,
    epochs=10,
    batch_size=128,
    validation_split=0.2
)

plot_history(history_max, "MaxPooling")

model_avg = build_model(pooling_type="avg")

history_avg = model_avg.fit(
    x_train, y_train,
    epochs=10,
    batch_size=128,
    validation_split=0.2
)

plot_history(history_avg, "AveragePooling")

model_d03 = build_model(dropout_rate=0.3)

history_d03 = model_d03.fit(
    x_train, y_train,
    epochs=10,
    batch_size=128,
    validation_split=0.2
)

plot_history(history_d03, "Dropout 0.3")

model_d07 = build_model(dropout_rate=0.7)

history_d07 = model_d07.fit(
    x_train, y_train,
    epochs=10,
    batch_size=128,
    validation_split=0.2
)

plot_history(history_d07, "Dropout 0.7")

model_k5 = build_model(kernel_size=5)

history_k5 = model_k5.fit(
    x_train, y_train,
    epochs=10,
    batch_size=128,
    validation_split=0.2
)

plot_history(history_k5, "Kernel Size 5")

model_s2 = build_model(stride=2)

history_s2 = model_s2.fit(
    x_train, y_train,
    epochs=10,
    batch_size=128,
    validation_split=0.2
)

plot_history(history_s2, "Stride 2")

model_deep = build_model(depth=[64, 128, 256])

history_deep = model_deep.fit(
    x_train, y_train,
    epochs=10,
    batch_size=128,
    validation_split=0.2
)

plot_history(history_deep, "Depth [64,128,256]")

"""نتیجه‌گیری و تحلیل نمودارها

با توجه به نمودارهای Accuracy و Loss که برای مدل‌های مختلف رسم شد، می‌توان مشاهده کرد که در تمام حالت‌ها، دقت آموزش در طول epochها افزایش یافته و مقدار loss کاهش پیدا کرده است که نشان‌دهنده یادگیری مناسب شبکه است. با این حال، در برخی مدل‌ها فاصله بین دقت آموزش و دقت اعتبارسنجی بیشتر شده که این موضوع می‌تواند نشانه‌ای از overfitting باشد.

در مقایسه بین دو روش MaxPooling و AveragePooling، نتایج نشان می‌دهد که استفاده از MaxPooling باعث افزایش دقت نهایی مدل و همگرایی سریع‌تر آن شده است. در حالی که AveragePooling روند یکنواخت‌تری دارد، اما دقت نهایی آن معمولاً کمتر از حالت MaxPooling است. به همین دلیل، MaxPooling برای این مسئله عملکرد مناسب‌تری داشته است.

بررسی اثر Dropout نشان می‌دهد که استفاده از مقدارهای متوسط باعث بهبود عملکرد مدل در داده‌های اعتبارسنجی می‌شود. در حالتی که مقدار Dropout زیاد انتخاب شده است، دقت آموزش کاهش پیدا کرده و مدل به‌خوبی قادر به یادگیری الگوهای داده نبوده که نشان‌دهنده underfitting است.

همچنین با تغییر اندازه کرنل، مشخص شد که کرنل 3×3 عملکرد بهتری نسبت به کرنل 5×5 دارد. کرنل بزرگ‌تر باعث افزایش پیچیدگی مدل شده و در برخی موارد منجر به کاهش دقت در داده‌های اعتبارسنجی شده است. این موضوع نشان می‌دهد که برای دیتاست Fashion-MNIST، کرنل‌های کوچک‌تر انتخاب مناسب‌تری هستند.

نتایج مربوط به تغییر مقدار Stride نشان داد که افزایش Stride باعث کاهش ابعاد feature map و در نتیجه کاهش دقت مدل می‌شود. در مقابل، استفاده از Stride برابر با 1 باعث حفظ اطلاعات مکانی تصویر و بهبود عملکرد مدل شده است.

در نهایت، بررسی تعداد فیلترها (Depth) نشان داد که افزایش تعداد فیلترها تا حد مشخصی باعث بهبود دقت مدل می‌شود، اما در صورت افزایش بیش از حد، فاصله بین دقت آموزش و اعتبارسنجی بیشتر شده و نشانه‌هایی از overfitting مشاهده می‌شود.

به طور کلی، نتایج این پروژه نشان می‌دهد که انتخاب مناسب معماری شبکه و تنظیم درست هایپرپارامترها نقش مهمی در بهبود عملکرد شبکه‌های کانولوشنی دارد و نمودارهای Accuracy و Loss ابزار مناسبی برای تحلیل رفتار مدل در فرآیند آموزش هستند.
"""