# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam

# Reproducibility
np.random.seed(42)
tf.random.set_seed(42)

# Generate non-linear data
X = np.linspace(-2 * np.pi, 2 * np.pi, 1000)
y = np.sin(X) + 0.1 * np.random.randn(len(X))  # Add noise

# Reshape for Keras
X = X.reshape(-1, 1)
y = y.reshape(-1, 1)

# Train / validation split
X_train, X_val, y_train, y_val = train_test_split(
    X, y, test_size=0.2, random_state=42
)

def build_model(hidden_units=32, learning_rate=0.001):
    model = Sequential([
        Dense(hidden_units, activation='relu', input_shape=(1,)),  # Layer 1 (Input)
        Dense(hidden_units, activation='relu'),                     # Layer 2
        Dense(hidden_units, activation='relu'),                     # Layer 3
        Dense(1)                                                     # Layer 4 (Output)
    ])

    model.compile(
        optimizer=Adam(learning_rate=learning_rate),
        loss='mse',
        metrics=['mae']
    )
    return model

configs = [
    {"hidden_units": 32, "learning_rate": 0.001, "label": "LR=0.001, Units=32"},
    {"hidden_units": 64, "learning_rate": 0.0005, "label": "LR=0.0005, Units=64"},
]

histories = {}
models = {}

for cfg in configs:
    print(f"Training model: {cfg['label']}")

    model = build_model(
        hidden_units=cfg["hidden_units"],
        learning_rate=cfg["learning_rate"]
    )

    history = model.fit(
        X_train, y_train,
        validation_data=(X_val, y_val),
        epochs=50,
        batch_size=32,
        verbose=0
    )

    histories[cfg["label"]] = history
    models[cfg["label"]] = model

plt.figure()
for label, history in histories.items():
    plt.plot(history.history['loss'], label=f'{label} - Train')
    plt.plot(history.history['val_loss'], linestyle='--', label=f'{label} - Val')

plt.xlabel("Epoch")
plt.ylabel("MSE Loss")
plt.title("Training vs Validation Loss")
plt.legend()
plt.show()

plt.figure()
for label, history in histories.items():
    plt.plot(history.history['mae'], label=f'{label} - Train')
    plt.plot(history.history['val_mae'], linestyle='--', label=f'{label} - Val')

plt.xlabel("Epoch")
plt.ylabel("MAE")
plt.title("Training vs Validation MAE")
plt.legend()
plt.show()

best_label = configs[1]["label"]
best_model = models[best_label]

y_pred = best_model.predict(X_val)

plt.figure()
plt.scatter(X_val, y_val, label="Actual", alpha=0.5)
plt.scatter(X_val, y_pred, label="Predicted", alpha=0.5)
plt.xlabel("X")
plt.ylabel("y")
plt.title(f"Predicted vs Actual ({best_label})")
plt.legend()
plt.show()